Repository ColindeGroot/pleasurable-ui, pull requests merged in 2025-05, with the labels that each got.

#27 #24 Fixed radio stations logos being too blurry and or small at home.…
  public/assets/radio-1.avif
  public/assets/radio-1.png
  public/assets/radio-1.webp
  public/css/head.css
  public/css/home.css
  views/index.liquid
  views/partials/header.liquid
Labels: bug

#58 starting style toevoegen
  public/css/popup.css
  views/partials/popup.liquid
Labels: enhancement

#50 #49 Added new card with base HTML and minimal css on testpage and made bookmark work with this new card
  public/assets/show-test.avif
  public/assets/show-test.png
  public/assets/show-test.webp
  public/css/card-dylan.css
  public/css/general.css
  server.js
  views/card-dylan.liquid
Labels: question

#61 popup v2 to main, with dynamic data and route for bookmarks
  public/assets/radioveronica-logo.png
  public/css/general.css
  public/css/popup-test.css
  public/css/popup.css
  public/css/style.css
  public/js/popup.js
  public/js/script.js
  server.js
  views/partials/head.liquid
  views/partials/popup.liquid
  views/radio.liquid
  views/testpage.liquid
Labels: enhancement
